# Generated by Django 4.2 on 2024-10-13 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_estado_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='id_estado',
            field=models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='app.estado'),
        ),
    ]
