# Generated by Django 5.1.5 on 2025-01-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_solicitud_id_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto_accesorio',
            fields=[
                ('id_repuesto_acc', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'repuesto_accesorio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipo_respuesto_acc',
            fields=[
                ('id_tipo_repuesto_acc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'tipo_repuesto_acc',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'managed': True},
        ),
    ]
