# Generated by Django 5.1.5 on 2025-01-15 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_repuesto_accesorio_tipo_respuesto_acc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='prestadora',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='repuesto_accesorio',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='telefono',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipo_equipo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipo_respuesto_acc',
            options={'managed': True},
        ),
    ]
