# Generated by Django 5.1.4 on 2025-01-16 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cliente_options_alter_equipo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prestadora',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='repuesto_accesorio',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='telefono',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipo_equipo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipo_respuesto_acc',
            options={'managed': False},
        ),
    ]
