# Generated by Django 5.1.5 on 2025-03-17 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_cliente_options_alter_equipo_options_and_more'),
    ]

    operations = [
        #migrations.RunSQL(
            #"ALTER TABLE app_solicitud RENAME TO solicitud;",
        #)
    ]
