# Generated by Django 5.1.4 on 2025-01-16 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_cliente_options_alter_equipo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='solicitud',
            table='solicitud',
        ),
    ]
