# Generated by Django 5.1.5 on 2025-04-07 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_solicitud_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'managed': True},
        ),
    ]
