# Generated by Django 5.1.5 on 2025-04-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_solicitud_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='solicitud',
            table='solicitud',
        ),
    ]
